/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Apteco.OrbitDashboardRefresher.APIClient.Client;
using Apteco.OrbitDashboardRefresher.APIClient.Model;

namespace Apteco.OrbitDashboardRefresher.APIClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFastStatsBuildsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns></returns>
        void FastStatsBuildsCancelFastStatsBuildJob (string dataViewName, string systemName, int? jobId);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> FastStatsBuildsCancelFastStatsBuildJobWithHttpInfo (string dataViewName, string systemName, int? jobId);
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>BuildJobDetail</returns>
        BuildJobDetail FastStatsBuildsCreateFastStatsBuildJob (string dataViewName, string systemName, BuildDefinition buildDefinition = null);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>ApiResponse of BuildJobDetail</returns>
        ApiResponse<BuildJobDetail> FastStatsBuildsCreateFastStatsBuildJobWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null);
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>BuildResult</returns>
        BuildResult FastStatsBuildsFastStatsBuildSync (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>ApiResponse of BuildResult</returns>
        ApiResponse<BuildResult> FastStatsBuildsFastStatsBuildSyncWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null);
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>BuildJobDetail</returns>
        BuildJobDetail FastStatsBuildsGetFastStatsBuildJob (string dataViewName, string systemName, int? jobId);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>ApiResponse of BuildJobDetail</returns>
        ApiResponse<BuildJobDetail> FastStatsBuildsGetFastStatsBuildJobWithHttpInfo (string dataViewName, string systemName, int? jobId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task FastStatsBuildsCancelFastStatsBuildJobAsync (string dataViewName, string systemName, int? jobId);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> FastStatsBuildsCancelFastStatsBuildJobAsyncWithHttpInfo (string dataViewName, string systemName, int? jobId);
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>Task of BuildJobDetail</returns>
        System.Threading.Tasks.Task<BuildJobDetail> FastStatsBuildsCreateFastStatsBuildJobAsync (string dataViewName, string systemName, BuildDefinition buildDefinition = null);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>Task of ApiResponse (BuildJobDetail)</returns>
        System.Threading.Tasks.Task<ApiResponse<BuildJobDetail>> FastStatsBuildsCreateFastStatsBuildJobAsyncWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null);
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>Task of BuildResult</returns>
        System.Threading.Tasks.Task<BuildResult> FastStatsBuildsFastStatsBuildSyncAsync (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>Task of ApiResponse (BuildResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<BuildResult>> FastStatsBuildsFastStatsBuildSyncAsyncWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null);
        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>Task of BuildJobDetail</returns>
        System.Threading.Tasks.Task<BuildJobDetail> FastStatsBuildsGetFastStatsBuildJobAsync (string dataViewName, string systemName, int? jobId);

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job
        /// </summary>
        /// <remarks>
        /// EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>Task of ApiResponse (BuildJobDetail)</returns>
        System.Threading.Tasks.Task<ApiResponse<BuildJobDetail>> FastStatsBuildsGetFastStatsBuildJobAsyncWithHttpInfo (string dataViewName, string systemName, int? jobId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FastStatsBuildsApi : IFastStatsBuildsApi
    {
        private Apteco.OrbitDashboardRefresher.APIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FastStatsBuildsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FastStatsBuildsApi(String basePath)
        {
            this.Configuration = new Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FastStatsBuildsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FastStatsBuildsApi(Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Apteco.OrbitDashboardRefresher.APIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns></returns>
        public void FastStatsBuildsCancelFastStatsBuildJob (string dataViewName, string systemName, int? jobId)
        {
             FastStatsBuildsCancelFastStatsBuildJobWithHttpInfo(dataViewName, systemName, jobId);
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> FastStatsBuildsCancelFastStatsBuildJobWithHttpInfo (string dataViewName, string systemName, int? jobId)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsCancelFastStatsBuildJob");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsCancelFastStatsBuildJob");
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new ApiException(400, "Missing required parameter 'jobId' when calling FastStatsBuildsApi->FastStatsBuildsCancelFastStatsBuildJob");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildJobs/{jobId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (jobId != null) localVarPathParams.Add("jobId", this.Configuration.ApiClient.ParameterToString(jobId)); // path parameter

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsCancelFastStatsBuildJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task FastStatsBuildsCancelFastStatsBuildJobAsync (string dataViewName, string systemName, int? jobId)
        {
             await FastStatsBuildsCancelFastStatsBuildJobAsyncWithHttpInfo(dataViewName, systemName, jobId);

        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Cancel a running data purchasing job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to cancel</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> FastStatsBuildsCancelFastStatsBuildJobAsyncWithHttpInfo (string dataViewName, string systemName, int? jobId)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsCancelFastStatsBuildJob");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsCancelFastStatsBuildJob");
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new ApiException(400, "Missing required parameter 'jobId' when calling FastStatsBuildsApi->FastStatsBuildsCancelFastStatsBuildJob");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildJobs/{jobId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (jobId != null) localVarPathParams.Add("jobId", this.Configuration.ApiClient.ParameterToString(jobId)); // path parameter

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsCancelFastStatsBuildJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>BuildJobDetail</returns>
        public BuildJobDetail FastStatsBuildsCreateFastStatsBuildJob (string dataViewName, string systemName, BuildDefinition buildDefinition = null)
        {
             ApiResponse<BuildJobDetail> localVarResponse = FastStatsBuildsCreateFastStatsBuildJobWithHttpInfo(dataViewName, systemName, buildDefinition);
             return localVarResponse.Data;
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>ApiResponse of BuildJobDetail</returns>
        public ApiResponse< BuildJobDetail > FastStatsBuildsCreateFastStatsBuildJobWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsCreateFastStatsBuildJob");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsCreateFastStatsBuildJob");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildJobs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (buildDefinition != null && buildDefinition.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(buildDefinition); // http body (model) parameter
            }
            else
            {
                localVarPostBody = buildDefinition; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsCreateFastStatsBuildJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BuildJobDetail>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BuildJobDetail) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BuildJobDetail)));
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>Task of BuildJobDetail</returns>
        public async System.Threading.Tasks.Task<BuildJobDetail> FastStatsBuildsCreateFastStatsBuildJobAsync (string dataViewName, string systemName, BuildDefinition buildDefinition = null)
        {
             ApiResponse<BuildJobDetail> localVarResponse = await FastStatsBuildsCreateFastStatsBuildJobAsyncWithHttpInfo(dataViewName, systemName, buildDefinition);
             return localVarResponse.Data;

        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Create a new job to builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <returns>Task of ApiResponse (BuildJobDetail)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BuildJobDetail>> FastStatsBuildsCreateFastStatsBuildJobAsyncWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsCreateFastStatsBuildJob");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsCreateFastStatsBuildJob");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildJobs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (buildDefinition != null && buildDefinition.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(buildDefinition); // http body (model) parameter
            }
            else
            {
                localVarPostBody = buildDefinition; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsCreateFastStatsBuildJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BuildJobDetail>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BuildJobDetail) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BuildJobDetail)));
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>BuildResult</returns>
        public BuildResult FastStatsBuildsFastStatsBuildSync (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null)
        {
             ApiResponse<BuildResult> localVarResponse = FastStatsBuildsFastStatsBuildSyncWithHttpInfo(dataViewName, systemName, buildDefinition, timeoutInSeconds);
             return localVarResponse.Data;
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>ApiResponse of BuildResult</returns>
        public ApiResponse< BuildResult > FastStatsBuildsFastStatsBuildSyncWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsFastStatsBuildSync");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsFastStatsBuildSync");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (buildDefinition != null && buildDefinition.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(buildDefinition); // http body (model) parameter
            }
            else
            {
                localVarPostBody = buildDefinition; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsFastStatsBuildSync", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BuildResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BuildResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BuildResult)));
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>Task of BuildResult</returns>
        public async System.Threading.Tasks.Task<BuildResult> FastStatsBuildsFastStatsBuildSyncAsync (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null)
        {
             ApiResponse<BuildResult> localVarResponse = await FastStatsBuildsFastStatsBuildSyncAsyncWithHttpInfo(dataViewName, systemName, buildDefinition, timeoutInSeconds);
             return localVarResponse.Data;

        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Builds a FastStats system from the given definition EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="buildDefinition">The details needed to build the system (optional)</param>
        /// <param name="timeoutInSeconds">The number of seconds before the request will time out.  Leave unspecified to use the default value given in the build service&#39;s configuration (optional)</param>
        /// <returns>Task of ApiResponse (BuildResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BuildResult>> FastStatsBuildsFastStatsBuildSyncAsyncWithHttpInfo (string dataViewName, string systemName, BuildDefinition buildDefinition = null, int? timeoutInSeconds = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsFastStatsBuildSync");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsFastStatsBuildSync");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildSync";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (timeoutInSeconds != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "timeoutInSeconds", timeoutInSeconds)); // query parameter
            if (buildDefinition != null && buildDefinition.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(buildDefinition); // http body (model) parameter
            }
            else
            {
                localVarPostBody = buildDefinition; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsFastStatsBuildSync", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BuildResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BuildResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BuildResult)));
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>BuildJobDetail</returns>
        public BuildJobDetail FastStatsBuildsGetFastStatsBuildJob (string dataViewName, string systemName, int? jobId)
        {
             ApiResponse<BuildJobDetail> localVarResponse = FastStatsBuildsGetFastStatsBuildJobWithHttpInfo(dataViewName, systemName, jobId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>ApiResponse of BuildJobDetail</returns>
        public ApiResponse< BuildJobDetail > FastStatsBuildsGetFastStatsBuildJobWithHttpInfo (string dataViewName, string systemName, int? jobId)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsGetFastStatsBuildJob");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsGetFastStatsBuildJob");
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new ApiException(400, "Missing required parameter 'jobId' when calling FastStatsBuildsApi->FastStatsBuildsGetFastStatsBuildJob");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildJobs/{jobId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (jobId != null) localVarPathParams.Add("jobId", this.Configuration.ApiClient.ParameterToString(jobId)); // path parameter

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsGetFastStatsBuildJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BuildJobDetail>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BuildJobDetail) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BuildJobDetail)));
        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>Task of BuildJobDetail</returns>
        public async System.Threading.Tasks.Task<BuildJobDetail> FastStatsBuildsGetFastStatsBuildJobAsync (string dataViewName, string systemName, int? jobId)
        {
             ApiResponse<BuildJobDetail> localVarResponse = await FastStatsBuildsGetFastStatsBuildJobAsyncWithHttpInfo(dataViewName, systemName, jobId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// EXPERIMENTAL: Requires OrbitAdmin: Get the status of a running FastStats build job EXPERIMENTAL  This endpoint is only available for users with the OrbitAdmin role
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="jobId">The id of the job to get the status for.</param>
        /// <returns>Task of ApiResponse (BuildJobDetail)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BuildJobDetail>> FastStatsBuildsGetFastStatsBuildJobAsyncWithHttpInfo (string dataViewName, string systemName, int? jobId)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling FastStatsBuildsApi->FastStatsBuildsGetFastStatsBuildJob");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling FastStatsBuildsApi->FastStatsBuildsGetFastStatsBuildJob");
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new ApiException(400, "Missing required parameter 'jobId' when calling FastStatsBuildsApi->FastStatsBuildsGetFastStatsBuildJob");

            var localVarPath = "/{dataViewName}/FastStatsBuilds/{systemName}/BuildJobs/{jobId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (jobId != null) localVarPathParams.Add("jobId", this.Configuration.ApiClient.ParameterToString(jobId)); // path parameter

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FastStatsBuildsGetFastStatsBuildJob", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BuildJobDetail>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BuildJobDetail) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BuildJobDetail)));
        }

    }
}
