/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Apteco.OrbitDashboardRefresher.APIClient.Client;
using Apteco.OrbitDashboardRefresher.APIClient.Model;

namespace Apteco.OrbitDashboardRefresher.APIClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMetaDataApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>MetaDataDetails</returns>
        MetaDataDetails MetaDataCreateSystemMetaData (string dataViewName, string systemName, List<MetaDataItem> requestData = null);

        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>ApiResponse of MetaDataDetails</returns>
        ApiResponse<MetaDataDetails> MetaDataCreateSystemMetaDataWithHttpInfo (string dataViewName, string systemName, List<MetaDataItem> requestData = null);
        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>MetaDataDetails</returns>
        MetaDataDetails MetaDataGetSystemMetaData (string dataViewName, string systemName);

        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>ApiResponse of MetaDataDetails</returns>
        ApiResponse<MetaDataDetails> MetaDataGetSystemMetaDataWithHttpInfo (string dataViewName, string systemName);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>Task of MetaDataDetails</returns>
        System.Threading.Tasks.Task<MetaDataDetails> MetaDataCreateSystemMetaDataAsync (string dataViewName, string systemName, List<MetaDataItem> requestData = null);

        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>Task of ApiResponse (MetaDataDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<MetaDataDetails>> MetaDataCreateSystemMetaDataAsyncWithHttpInfo (string dataViewName, string systemName, List<MetaDataItem> requestData = null);
        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>Task of MetaDataDetails</returns>
        System.Threading.Tasks.Task<MetaDataDetails> MetaDataGetSystemMetaDataAsync (string dataViewName, string systemName);

        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system
        /// </summary>
        /// <remarks>
        /// UNDER DEVELOPMENT
        /// </remarks>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>Task of ApiResponse (MetaDataDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<MetaDataDetails>> MetaDataGetSystemMetaDataAsyncWithHttpInfo (string dataViewName, string systemName);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MetaDataApi : IMetaDataApi
    {
        private Apteco.OrbitDashboardRefresher.APIClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaDataApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MetaDataApi(String basePath)
        {
            this.Configuration = new Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetaDataApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MetaDataApi(Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Apteco.OrbitDashboardRefresher.APIClient.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Apteco.OrbitDashboardRefresher.APIClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>MetaDataDetails</returns>
        public MetaDataDetails MetaDataCreateSystemMetaData (string dataViewName, string systemName, List<MetaDataItem> requestData = null)
        {
             ApiResponse<MetaDataDetails> localVarResponse = MetaDataCreateSystemMetaDataWithHttpInfo(dataViewName, systemName, requestData);
             return localVarResponse.Data;
        }

        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>ApiResponse of MetaDataDetails</returns>
        public ApiResponse< MetaDataDetails > MetaDataCreateSystemMetaDataWithHttpInfo (string dataViewName, string systemName, List<MetaDataItem> requestData = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling MetaDataApi->MetaDataCreateSystemMetaData");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling MetaDataApi->MetaDataCreateSystemMetaData");

            var localVarPath = "./{dataViewName}/MetaData/{systemName}/Items";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (requestData != null && requestData.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestData); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestData; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MetaDataCreateSystemMetaData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MetaDataDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (MetaDataDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MetaDataDetails)));
        }

        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>Task of MetaDataDetails</returns>
        public async System.Threading.Tasks.Task<MetaDataDetails> MetaDataCreateSystemMetaDataAsync (string dataViewName, string systemName, List<MetaDataItem> requestData = null)
        {
             ApiResponse<MetaDataDetails> localVarResponse = await MetaDataCreateSystemMetaDataAsyncWithHttpInfo(dataViewName, systemName, requestData);
             return localVarResponse.Data;

        }

        /// <summary>
        /// UNDER DEVELOPMENT: Creates system meta data items from the given details UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <param name="requestData">The details of the meta data items to add (optional)</param>
        /// <returns>Task of ApiResponse (MetaDataDetails)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MetaDataDetails>> MetaDataCreateSystemMetaDataAsyncWithHttpInfo (string dataViewName, string systemName, List<MetaDataItem> requestData = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling MetaDataApi->MetaDataCreateSystemMetaData");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling MetaDataApi->MetaDataCreateSystemMetaData");

            var localVarPath = "./{dataViewName}/MetaData/{systemName}/Items";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter
            if (requestData != null && requestData.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(requestData); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestData; // byte array
            }

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MetaDataCreateSystemMetaData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MetaDataDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (MetaDataDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MetaDataDetails)));
        }

        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>MetaDataDetails</returns>
        public MetaDataDetails MetaDataGetSystemMetaData (string dataViewName, string systemName)
        {
             ApiResponse<MetaDataDetails> localVarResponse = MetaDataGetSystemMetaDataWithHttpInfo(dataViewName, systemName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>ApiResponse of MetaDataDetails</returns>
        public ApiResponse< MetaDataDetails > MetaDataGetSystemMetaDataWithHttpInfo (string dataViewName, string systemName)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling MetaDataApi->MetaDataGetSystemMetaData");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling MetaDataApi->MetaDataGetSystemMetaData");

            var localVarPath = "./{dataViewName}/MetaData/{systemName}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MetaDataGetSystemMetaData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MetaDataDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (MetaDataDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MetaDataDetails)));
        }

        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>Task of MetaDataDetails</returns>
        public async System.Threading.Tasks.Task<MetaDataDetails> MetaDataGetSystemMetaDataAsync (string dataViewName, string systemName)
        {
             ApiResponse<MetaDataDetails> localVarResponse = await MetaDataGetSystemMetaDataAsyncWithHttpInfo(dataViewName, systemName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// UNDER DEVELOPMENT: Returns a list of meta data for the system UNDER DEVELOPMENT
        /// </summary>
        /// <exception cref="Apteco.OrbitDashboardRefresher.APIClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="systemName">The name of the FastStats system to act on</param>
        /// <returns>Task of ApiResponse (MetaDataDetails)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MetaDataDetails>> MetaDataGetSystemMetaDataAsyncWithHttpInfo (string dataViewName, string systemName)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling MetaDataApi->MetaDataGetSystemMetaData");
            // verify the required parameter 'systemName' is set
            if (systemName == null)
                throw new ApiException(400, "Missing required parameter 'systemName' when calling MetaDataApi->MetaDataGetSystemMetaData");

            var localVarPath = "./{dataViewName}/MetaData/{systemName}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (systemName != null) localVarPathParams.Add("systemName", this.Configuration.ApiClient.ParameterToString(systemName)); // path parameter

            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MetaDataGetSystemMetaData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MetaDataDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (MetaDataDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MetaDataDetails)));
        }

    }
}
