/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.OrbitDashboardRefresher.APIClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitDashboardRefresher.APIClient.Model
{
    /// <summary>
    /// ConvertAudienceToCampaignDetails
    /// </summary>
    [DataContract]
    public partial class ConvertAudienceToCampaignDetails :  IEquatable<ConvertAudienceToCampaignDetails>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConvertAudienceToCampaignDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConvertAudienceToCampaignDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConvertAudienceToCampaignDetails" /> class.
        /// </summary>
        /// <param name="description">The description to use for the new campaign (required).</param>
        /// <param name="channelId">The id of the channel to use in the delivery step of the new campaign (required).</param>
        /// <param name="broadcastMessageName">The name of the message name to use for the channel (assuming it is a broadcast channel).</param>
        /// <param name="broadcastListName">The name of the list name to use for the channel (assuming it is a broadcast channel) - defaults to BroadcastMessageName if not supplied.</param>
        /// <param name="includeFinalPool">Whether to create a pool for the people to flow into or not (so they they can be recorded and referred to).</param>
        /// <param name="pathToCampaign">The path of (possibly non-existent) areas going from the programme to where the campaign is to be saved.</param>
        /// <param name="exportVariables">Details for each column being added to the content step.</param>
        public ConvertAudienceToCampaignDetails(string description = default(string), string channelId = default(string), string broadcastMessageName = default(string), string broadcastListName = default(string), bool? includeFinalPool = default(bool?), List<string> pathToCampaign = default(List<string>), List<Column> exportVariables = default(List<Column>))
        {
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for ConvertAudienceToCampaignDetails and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            // to ensure "channelId" is required (not null)
            if (channelId == null)
            {
                throw new InvalidDataException("channelId is a required property for ConvertAudienceToCampaignDetails and cannot be null");
            }
            else
            {
                this.ChannelId = channelId;
            }
            this.BroadcastMessageName = broadcastMessageName;
            this.BroadcastListName = broadcastListName;
            this.IncludeFinalPool = includeFinalPool;
            this.PathToCampaign = pathToCampaign;
            this.ExportVariables = exportVariables;
        }
        
        /// <summary>
        /// The description to use for the new campaign
        /// </summary>
        /// <value>The description to use for the new campaign</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// The id of the channel to use in the delivery step of the new campaign
        /// </summary>
        /// <value>The id of the channel to use in the delivery step of the new campaign</value>
        [DataMember(Name="channelId", EmitDefaultValue=false)]
        public string ChannelId { get; set; }

        /// <summary>
        /// The name of the message name to use for the channel (assuming it is a broadcast channel)
        /// </summary>
        /// <value>The name of the message name to use for the channel (assuming it is a broadcast channel)</value>
        [DataMember(Name="broadcastMessageName", EmitDefaultValue=false)]
        public string BroadcastMessageName { get; set; }

        /// <summary>
        /// The name of the list name to use for the channel (assuming it is a broadcast channel) - defaults to BroadcastMessageName if not supplied
        /// </summary>
        /// <value>The name of the list name to use for the channel (assuming it is a broadcast channel) - defaults to BroadcastMessageName if not supplied</value>
        [DataMember(Name="broadcastListName", EmitDefaultValue=false)]
        public string BroadcastListName { get; set; }

        /// <summary>
        /// Whether to create a pool for the people to flow into or not (so they they can be recorded and referred to)
        /// </summary>
        /// <value>Whether to create a pool for the people to flow into or not (so they they can be recorded and referred to)</value>
        [DataMember(Name="includeFinalPool", EmitDefaultValue=false)]
        public bool? IncludeFinalPool { get; set; }

        /// <summary>
        /// The path of (possibly non-existent) areas going from the programme to where the campaign is to be saved
        /// </summary>
        /// <value>The path of (possibly non-existent) areas going from the programme to where the campaign is to be saved</value>
        [DataMember(Name="pathToCampaign", EmitDefaultValue=false)]
        public List<string> PathToCampaign { get; set; }

        /// <summary>
        /// Details for each column being added to the content step
        /// </summary>
        /// <value>Details for each column being added to the content step</value>
        [DataMember(Name="exportVariables", EmitDefaultValue=false)]
        public List<Column> ExportVariables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConvertAudienceToCampaignDetails {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ChannelId: ").Append(ChannelId).Append("\n");
            sb.Append("  BroadcastMessageName: ").Append(BroadcastMessageName).Append("\n");
            sb.Append("  BroadcastListName: ").Append(BroadcastListName).Append("\n");
            sb.Append("  IncludeFinalPool: ").Append(IncludeFinalPool).Append("\n");
            sb.Append("  PathToCampaign: ").Append(PathToCampaign).Append("\n");
            sb.Append("  ExportVariables: ").Append(ExportVariables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConvertAudienceToCampaignDetails);
        }

        /// <summary>
        /// Returns true if ConvertAudienceToCampaignDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of ConvertAudienceToCampaignDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConvertAudienceToCampaignDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.ChannelId == input.ChannelId ||
                    (this.ChannelId != null &&
                    this.ChannelId.Equals(input.ChannelId))
                ) && 
                (
                    this.BroadcastMessageName == input.BroadcastMessageName ||
                    (this.BroadcastMessageName != null &&
                    this.BroadcastMessageName.Equals(input.BroadcastMessageName))
                ) && 
                (
                    this.BroadcastListName == input.BroadcastListName ||
                    (this.BroadcastListName != null &&
                    this.BroadcastListName.Equals(input.BroadcastListName))
                ) && 
                (
                    this.IncludeFinalPool == input.IncludeFinalPool ||
                    (this.IncludeFinalPool != null &&
                    this.IncludeFinalPool.Equals(input.IncludeFinalPool))
                ) && 
                (
                    this.PathToCampaign == input.PathToCampaign ||
                    this.PathToCampaign != null &&
                    this.PathToCampaign.SequenceEqual(input.PathToCampaign)
                ) && 
                (
                    this.ExportVariables == input.ExportVariables ||
                    this.ExportVariables != null &&
                    this.ExportVariables.SequenceEqual(input.ExportVariables)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.ChannelId != null)
                    hashCode = hashCode * 59 + this.ChannelId.GetHashCode();
                if (this.BroadcastMessageName != null)
                    hashCode = hashCode * 59 + this.BroadcastMessageName.GetHashCode();
                if (this.BroadcastListName != null)
                    hashCode = hashCode * 59 + this.BroadcastListName.GetHashCode();
                if (this.IncludeFinalPool != null)
                    hashCode = hashCode * 59 + this.IncludeFinalPool.GetHashCode();
                if (this.PathToCampaign != null)
                    hashCode = hashCode * 59 + this.PathToCampaign.GetHashCode();
                if (this.ExportVariables != null)
                    hashCode = hashCode * 59 + this.ExportVariables.GetHashCode();
                return hashCode;
            }
        }
    }

}
