/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitDashboardRefresher.APIClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitDashboardRefresher.APIClient.Model
{
    /// <summary>
    /// The details for any pre-defined dashboard items, that aren&#39;t specified using dimensions and measures
    /// </summary>
    [DataContract]
    public partial class DashboardItemDataSpecification :  IEquatable<DashboardItemDataSpecification>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DashboardItemDataSpecification" /> class.
        /// </summary>
        /// <param name="cubeSpecification">The details needed to define a cube-based item.</param>
        /// <param name="paretoSpecification">The details needed to define a Pareto item.</param>
        /// <param name="vennSpecification">The details needed to define a Venn item.</param>
        public DashboardItemDataSpecification(CubeSpecification cubeSpecification = default(CubeSpecification), ParetoSpecification paretoSpecification = default(ParetoSpecification), VennSpecification vennSpecification = default(VennSpecification))
        {
            this.CubeSpecification = cubeSpecification;
            this.ParetoSpecification = paretoSpecification;
            this.VennSpecification = vennSpecification;
        }
        
        /// <summary>
        /// The details needed to define a cube-based item
        /// </summary>
        /// <value>The details needed to define a cube-based item</value>
        [DataMember(Name="cubeSpecification", EmitDefaultValue=false)]
        public CubeSpecification CubeSpecification { get; set; }

        /// <summary>
        /// The details needed to define a Pareto item
        /// </summary>
        /// <value>The details needed to define a Pareto item</value>
        [DataMember(Name="paretoSpecification", EmitDefaultValue=false)]
        public ParetoSpecification ParetoSpecification { get; set; }

        /// <summary>
        /// The details needed to define a Venn item
        /// </summary>
        /// <value>The details needed to define a Venn item</value>
        [DataMember(Name="vennSpecification", EmitDefaultValue=false)]
        public VennSpecification VennSpecification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DashboardItemDataSpecification {\n");
            sb.Append("  CubeSpecification: ").Append(CubeSpecification).Append("\n");
            sb.Append("  ParetoSpecification: ").Append(ParetoSpecification).Append("\n");
            sb.Append("  VennSpecification: ").Append(VennSpecification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DashboardItemDataSpecification);
        }

        /// <summary>
        /// Returns true if DashboardItemDataSpecification instances are equal
        /// </summary>
        /// <param name="input">Instance of DashboardItemDataSpecification to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DashboardItemDataSpecification input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CubeSpecification == input.CubeSpecification ||
                    (this.CubeSpecification != null &&
                    this.CubeSpecification.Equals(input.CubeSpecification))
                ) && 
                (
                    this.ParetoSpecification == input.ParetoSpecification ||
                    (this.ParetoSpecification != null &&
                    this.ParetoSpecification.Equals(input.ParetoSpecification))
                ) && 
                (
                    this.VennSpecification == input.VennSpecification ||
                    (this.VennSpecification != null &&
                    this.VennSpecification.Equals(input.VennSpecification))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CubeSpecification != null)
                    hashCode = hashCode * 59 + this.CubeSpecification.GetHashCode();
                if (this.ParetoSpecification != null)
                    hashCode = hashCode * 59 + this.ParetoSpecification.GetHashCode();
                if (this.VennSpecification != null)
                    hashCode = hashCode * 59 + this.VennSpecification.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
