/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitDashboardRefresher.APIClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitDashboardRefresher.APIClient.Model
{
    /// <summary>
    /// FacebookEntity
    /// </summary>
    [DataContract]
    public partial class FacebookEntity :  IEquatable<FacebookEntity>, IValidatableObject
    {
        /// <summary>
        /// Defines FacebookEntityType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FacebookEntityTypeEnum
        {
            
            /// <summary>
            /// Enum App for value: App
            /// </summary>
            [EnumMember(Value = "App")]
            App = 1,
            
            /// <summary>
            /// Enum Page for value: Page
            /// </summary>
            [EnumMember(Value = "Page")]
            Page = 2
        }

        /// <summary>
        /// Gets or Sets FacebookEntityType
        /// </summary>
        [DataMember(Name="facebookEntityType", EmitDefaultValue=false)]
        public FacebookEntityTypeEnum FacebookEntityType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FacebookEntity" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FacebookEntity() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FacebookEntity" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="facebookEntityType">facebookEntityType (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="systemName">systemName (required).</param>
        /// <param name="permissions">permissions (required).</param>
        /// <param name="valid">valid (required).</param>
        /// <param name="appId">appId (required).</param>
        public FacebookEntity(int? id = default(int?), FacebookEntityTypeEnum facebookEntityType = default(FacebookEntityTypeEnum), string name = default(string), string systemName = default(string), List<string> permissions = default(List<string>), bool? valid = default(bool?), int? appId = default(int?))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for FacebookEntity and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "facebookEntityType" is required (not null)
            if (facebookEntityType == null)
            {
                throw new InvalidDataException("facebookEntityType is a required property for FacebookEntity and cannot be null");
            }
            else
            {
                this.FacebookEntityType = facebookEntityType;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for FacebookEntity and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "systemName" is required (not null)
            if (systemName == null)
            {
                throw new InvalidDataException("systemName is a required property for FacebookEntity and cannot be null");
            }
            else
            {
                this.SystemName = systemName;
            }
            // to ensure "permissions" is required (not null)
            if (permissions == null)
            {
                throw new InvalidDataException("permissions is a required property for FacebookEntity and cannot be null");
            }
            else
            {
                this.Permissions = permissions;
            }
            // to ensure "valid" is required (not null)
            if (valid == null)
            {
                throw new InvalidDataException("valid is a required property for FacebookEntity and cannot be null");
            }
            else
            {
                this.Valid = valid;
            }
            // to ensure "appId" is required (not null)
            if (appId == null)
            {
                throw new InvalidDataException("appId is a required property for FacebookEntity and cannot be null");
            }
            else
            {
                this.AppId = appId;
            }
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }


        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets SystemName
        /// </summary>
        [DataMember(Name="systemName", EmitDefaultValue=false)]
        public string SystemName { get; set; }

        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [DataMember(Name="permissions", EmitDefaultValue=false)]
        public List<string> Permissions { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [DataMember(Name="valid", EmitDefaultValue=false)]
        public bool? Valid { get; set; }

        /// <summary>
        /// Gets or Sets AppId
        /// </summary>
        [DataMember(Name="appId", EmitDefaultValue=false)]
        public int? AppId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FacebookEntity {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FacebookEntityType: ").Append(FacebookEntityType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SystemName: ").Append(SystemName).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FacebookEntity);
        }

        /// <summary>
        /// Returns true if FacebookEntity instances are equal
        /// </summary>
        /// <param name="input">Instance of FacebookEntity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FacebookEntity input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.FacebookEntityType == input.FacebookEntityType ||
                    (this.FacebookEntityType != null &&
                    this.FacebookEntityType.Equals(input.FacebookEntityType))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.SystemName == input.SystemName ||
                    (this.SystemName != null &&
                    this.SystemName.Equals(input.SystemName))
                ) && 
                (
                    this.Permissions == input.Permissions ||
                    this.Permissions != null &&
                    this.Permissions.SequenceEqual(input.Permissions)
                ) && 
                (
                    this.Valid == input.Valid ||
                    (this.Valid != null &&
                    this.Valid.Equals(input.Valid))
                ) && 
                (
                    this.AppId == input.AppId ||
                    (this.AppId != null &&
                    this.AppId.Equals(input.AppId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.FacebookEntityType != null)
                    hashCode = hashCode * 59 + this.FacebookEntityType.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.SystemName != null)
                    hashCode = hashCode * 59 + this.SystemName.GetHashCode();
                if (this.Permissions != null)
                    hashCode = hashCode * 59 + this.Permissions.GetHashCode();
                if (this.Valid != null)
                    hashCode = hashCode * 59 + this.Valid.GetHashCode();
                if (this.AppId != null)
                    hashCode = hashCode * 59 + this.AppId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
