/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitDashboardRefresher.APIClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitDashboardRefresher.APIClient.Model
{
    /// <summary>
    /// Display details for a user that was invalid for being added or removed  from sharing a particular shareable item
    /// </summary>
    [DataContract]
    public partial class InvalidToShareUserDisplayDetails :  IEquatable<InvalidToShareUserDisplayDetails>, IValidatableObject
    {
        /// <summary>
        /// The reason why the user was not valid for updating the share
        /// </summary>
        /// <value>The reason why the user was not valid for updating the share</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReasonEnum
        {
            
            /// <summary>
            /// Enum ShareableAlreadySharedToUser for value: ShareableAlreadySharedToUser
            /// </summary>
            [EnumMember(Value = "ShareableAlreadySharedToUser")]
            ShareableAlreadySharedToUser = 1,
            
            /// <summary>
            /// Enum ShareableNotSharedToUser for value: ShareableNotSharedToUser
            /// </summary>
            [EnumMember(Value = "ShareableNotSharedToUser")]
            ShareableNotSharedToUser = 2,
            
            /// <summary>
            /// Enum ShareableOwnedByUser for value: ShareableOwnedByUser
            /// </summary>
            [EnumMember(Value = "ShareableOwnedByUser")]
            ShareableOwnedByUser = 3,
            
            /// <summary>
            /// Enum InvalidEmailDomain for value: InvalidEmailDomain
            /// </summary>
            [EnumMember(Value = "InvalidEmailDomain")]
            InvalidEmailDomain = 4
        }

        /// <summary>
        /// The reason why the user was not valid for updating the share
        /// </summary>
        /// <value>The reason why the user was not valid for updating the share</value>
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public ReasonEnum Reason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidToShareUserDisplayDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InvalidToShareUserDisplayDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InvalidToShareUserDisplayDetails" /> class.
        /// </summary>
        /// <param name="reason">The reason why the user was not valid for updating the share (required).</param>
        /// <param name="id">The user&#39;s id (required).</param>
        /// <param name="username">The user&#39;s username (required).</param>
        /// <param name="firstname">The user&#39;s first name (required).</param>
        /// <param name="surname">The user&#39;s surname (required).</param>
        /// <param name="emailAddress">The user&#39;s email address (required).</param>
        public InvalidToShareUserDisplayDetails(ReasonEnum reason = default(ReasonEnum), int? id = default(int?), string username = default(string), string firstname = default(string), string surname = default(string), string emailAddress = default(string))
        {
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new InvalidDataException("reason is a required property for InvalidToShareUserDisplayDetails and cannot be null");
            }
            else
            {
                this.Reason = reason;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for InvalidToShareUserDisplayDetails and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new InvalidDataException("username is a required property for InvalidToShareUserDisplayDetails and cannot be null");
            }
            else
            {
                this.Username = username;
            }
            // to ensure "firstname" is required (not null)
            if (firstname == null)
            {
                throw new InvalidDataException("firstname is a required property for InvalidToShareUserDisplayDetails and cannot be null");
            }
            else
            {
                this.Firstname = firstname;
            }
            // to ensure "surname" is required (not null)
            if (surname == null)
            {
                throw new InvalidDataException("surname is a required property for InvalidToShareUserDisplayDetails and cannot be null");
            }
            else
            {
                this.Surname = surname;
            }
            // to ensure "emailAddress" is required (not null)
            if (emailAddress == null)
            {
                throw new InvalidDataException("emailAddress is a required property for InvalidToShareUserDisplayDetails and cannot be null");
            }
            else
            {
                this.EmailAddress = emailAddress;
            }
        }
        

        /// <summary>
        /// The user&#39;s id
        /// </summary>
        /// <value>The user&#39;s id</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// The user&#39;s username
        /// </summary>
        /// <value>The user&#39;s username</value>
        [DataMember(Name="username", EmitDefaultValue=false)]
        public string Username { get; set; }

        /// <summary>
        /// The user&#39;s first name
        /// </summary>
        /// <value>The user&#39;s first name</value>
        [DataMember(Name="firstname", EmitDefaultValue=false)]
        public string Firstname { get; set; }

        /// <summary>
        /// The user&#39;s surname
        /// </summary>
        /// <value>The user&#39;s surname</value>
        [DataMember(Name="surname", EmitDefaultValue=false)]
        public string Surname { get; set; }

        /// <summary>
        /// The user&#39;s email address
        /// </summary>
        /// <value>The user&#39;s email address</value>
        [DataMember(Name="emailAddress", EmitDefaultValue=false)]
        public string EmailAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvalidToShareUserDisplayDetails {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Firstname: ").Append(Firstname).Append("\n");
            sb.Append("  Surname: ").Append(Surname).Append("\n");
            sb.Append("  EmailAddress: ").Append(EmailAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InvalidToShareUserDisplayDetails);
        }

        /// <summary>
        /// Returns true if InvalidToShareUserDisplayDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of InvalidToShareUserDisplayDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvalidToShareUserDisplayDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Reason == input.Reason ||
                    (this.Reason != null &&
                    this.Reason.Equals(input.Reason))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.Firstname == input.Firstname ||
                    (this.Firstname != null &&
                    this.Firstname.Equals(input.Firstname))
                ) && 
                (
                    this.Surname == input.Surname ||
                    (this.Surname != null &&
                    this.Surname.Equals(input.Surname))
                ) && 
                (
                    this.EmailAddress == input.EmailAddress ||
                    (this.EmailAddress != null &&
                    this.EmailAddress.Equals(input.EmailAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Reason != null)
                    hashCode = hashCode * 59 + this.Reason.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Username != null)
                    hashCode = hashCode * 59 + this.Username.GetHashCode();
                if (this.Firstname != null)
                    hashCode = hashCode * 59 + this.Firstname.GetHashCode();
                if (this.Surname != null)
                    hashCode = hashCode * 59 + this.Surname.GetHashCode();
                if (this.EmailAddress != null)
                    hashCode = hashCode * 59 + this.EmailAddress.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
