/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Apteco.OrbitDashboardRefresher.APIClient.Client.SwaggerDateConverter;

namespace Apteco.OrbitDashboardRefresher.APIClient.Model
{
    /// <summary>
    /// Details used to modify an audience for a given user
    /// </summary>
    [DataContract]
    public partial class ModifyUserAudience :  IEquatable<ModifyUserAudience>, IValidatableObject
    {
        /// <summary>
        /// The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored
        /// </summary>
        /// <value>The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModificationTypeEnum
        {
            
            /// <summary>
            /// Enum Modify for value: Modify
            /// </summary>
            [EnumMember(Value = "Modify")]
            Modify = 1,
            
            /// <summary>
            /// Enum Delete for value: Delete
            /// </summary>
            [EnumMember(Value = "Delete")]
            Delete = 2,
            
            /// <summary>
            /// Enum Undelete for value: Undelete
            /// </summary>
            [EnumMember(Value = "Undelete")]
            Undelete = 3
        }

        /// <summary>
        /// The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored
        /// </summary>
        /// <value>The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored</value>
        [DataMember(Name="modificationType", EmitDefaultValue=false)]
        public ModificationTypeEnum ModificationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyUserAudience" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModifyUserAudience() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyUserAudience" /> class.
        /// </summary>
        /// <param name="audience">The audience to modify (required).</param>
        /// <param name="id">The id of the item to update (required).</param>
        /// <param name="modificationType">The type of modification to perform.  If the type is delete or undelete, any other specified item details will be ignored (required).</param>
        public ModifyUserAudience(ModifyUserAudienceDetail audience = default(ModifyUserAudienceDetail), int? id = default(int?), ModificationTypeEnum modificationType = default(ModificationTypeEnum))
        {
            // to ensure "audience" is required (not null)
            if (audience == null)
            {
                throw new InvalidDataException("audience is a required property for ModifyUserAudience and cannot be null");
            }
            else
            {
                this.Audience = audience;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for ModifyUserAudience and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "modificationType" is required (not null)
            if (modificationType == null)
            {
                throw new InvalidDataException("modificationType is a required property for ModifyUserAudience and cannot be null");
            }
            else
            {
                this.ModificationType = modificationType;
            }
        }
        
        /// <summary>
        /// The audience to modify
        /// </summary>
        /// <value>The audience to modify</value>
        [DataMember(Name="audience", EmitDefaultValue=false)]
        public ModifyUserAudienceDetail Audience { get; set; }

        /// <summary>
        /// The id of the item to update
        /// </summary>
        /// <value>The id of the item to update</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModifyUserAudience {\n");
            sb.Append("  Audience: ").Append(Audience).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ModificationType: ").Append(ModificationType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModifyUserAudience);
        }

        /// <summary>
        /// Returns true if ModifyUserAudience instances are equal
        /// </summary>
        /// <param name="input">Instance of ModifyUserAudience to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModifyUserAudience input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Audience == input.Audience ||
                    (this.Audience != null &&
                    this.Audience.Equals(input.Audience))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ModificationType == input.ModificationType ||
                    (this.ModificationType != null &&
                    this.ModificationType.Equals(input.ModificationType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Audience != null)
                    hashCode = hashCode * 59 + this.Audience.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ModificationType != null)
                    hashCode = hashCode * 59 + this.ModificationType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
